# - name: Create config dir
#   become: yes
#   shell: |
#     mkdir -p {{ app_dir }}/{{name}}/config

- name: Set up Unicorn runit service
  become: yes
  shell: |
    mkdir -p /etc/sv/{{ name }}-unicorn
    mkdir -p /etc/sv/{{ name }}-unicorn/log
    echo '#!/bin/sh' > /etc/sv/{{ name }}-unicorn/run
    echo 'cd {{ app_dir }} || exit 1' >> /etc/sv/{{ name }}-unicorn/run
    echo 'export HOME=/home/ubuntu' >> /etc/sv/{{ name }}-unicorn/run
    echo 'exec 2>&1' >> /etc/sv/{{ name }}-unicorn/run

    echo 'exec chpst -u {{ ansible_ssh_user }}:{{ ansible_ssh_user }} /home/ubuntu/.rbenv/shims/bundle exec unicorn  -E production -c {{ app_dir }}/config/unicorn.rb' >> /etc/sv/{{ name }}-unicorn/run
    chmod +x /etc/sv/{{ name }}-unicorn/run
    rm /etc/service/{{ name }}-unicorn
    ln -s /etc/sv/{{ name }}-unicorn /etc/service/{{ name }}-unicorn

- name: Set up Unicorn log runit service
  become: yes
  copy:
    content: |
      #!/bin/sh
      exec svlogd -tt /var/log/{{ name }}-unicorn
    dest: /etc/sv/{{ name }}-unicorn/log/run
    owner: root
    group: root
    mode: '0755'

- name: Ensure Unicorn log directory exists
  become: yes
  file:
    path: /var/log/{{ name }}-unicorn
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0755'

- name: Link Unicorn service to runit
  become: yes
  file:
    src: /etc/sv/{{ name }}-unicorn
    dest: /etc/service/{{ name }}-unicorn
    state: link
