# FIMXE This repeats for each target server, annoying but no big deal
- name: update local repository cache
  sudo: false
  local_action: git repo=${repo} dest=$ENV(HOME)/.ansible-cache-${name}
                version=$version

- name: create cache directory
  file: path=/home/${rsync_user}/.ansible-git-cache/
        state=directory
        owner=${rsync_user}

- name: sync repository to target system
  sudo: false
  local_action: command rsync -a --no-perms -e ssh
                $ENV(HOME)/.ansible-cache-${name}/
                ${rsync_user}@${inventory_hostname}:/home/${rsync_user}/.ansible-git-cache/${name}

- name: update deployment target directory
  git: repo=/home/${rsync_user}/.ansible-git-cache/${name}
       dest=$dest
       version=$version
