# FIMXE This repeats for each target server, annoying but no big deal
- name: update local repository cache
  local_action: git repo=$repo dest=$ENV(HOME)/.ansible-cache-${name}
                version=$version

- name: sync repository to target system
  local_action: command rsync -a --no-perms -e ssh
                $ENV(HOME)/.ansible-cache-${name}/
                ${rsync_user}@${inventory_hostname}:/home/${rsync_user}/ansible-cache-${name}

- name: update deployment target directory
  git: repo=/home/${rsync_user}/ansible-cache-${name}
       dest=$dest
       version=$version
