- name: init_symfony_app - update composer dependencies
  command: composer install
           chdir="{{dir}}"
  register: composer_result
  changed_when: "'Nothing to install or update' not in composer_result.stdout"

# TODO: Run some kind of setup script provided by the app, if it's present
