- name: install GPG key for dotdeb PHP repository
  apt_key: url='http://www.dotdeb.org/dotdeb.gpg'

- name: access dotdeb PHP repository (version 5.5)
  apt_repository: repo='deb http://packages.dotdeb.org wheezy-php55 all'
                  update_cache=yes

- name: install PHP 5 packages
  apt: pkg={{item}}
  with_items:
    - php5-dev
    - php5-cli
    - php5-apcu
    - php5-curl
    - php5-gmp
    - php5-intl
    - php5-memcached
    - php5-memcache
    - php5-mongo
    - php5-mysql
    - php5-pgsql
    - php5-redis
    - php5-sqlite
    - php5-xmlrpc

- name: install composer
  shell: curl -s http://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
         creates=/usr/local/bin/composer.phar

- name: update php.ini for php5-cli
  copy: src=../files/php.ini dest=/etc/php5/cli/php.ini
