- name: install rabbitmq-server
  apt: pkg=rabbitmq-server

- name: enable rabbitmq management
  shell: rabbitmq-plugins enable rabbitmq_management

- include_tasks: supervisorify.yml
  vars:
    service: rabbitmq-server
    command: /usr/lib/rabbitmq/bin/rabbitmq-server
    procname: rabbitmq_server
    daemon_environment: HOME=/tmp
