- include: install_nodejs.yml

- include: install_grunt.yml

- include: install_bower.yml

- include: install_ruby.yml

- name: install haml gem
  gem: name=haml state=present

- name: install sass gem
  gem: name=sass state=present

- name: install sass-css-importer gem
  gem: name=sass-css-importer state=present version=1.0.0.beta.0

