# This copies a custom install script to the server, and runs that to install ffmpeg
# The packages provided by Ubuntu are bad, and other PPAs don't provide a version
# that's as easy to configure

- name: copy ffmpeg install script
  copy: src=common/files/install_ffmpeg.sh
        dest=/home/control/install_ffmpeg.sh

- name: install ffmpeg
  command: /usr/local/control/install_ffmpeg.sh creates=/usr/local/bin/ffmpeg
