- name: install mysql
  apt: pkg=mysql-server

- name: install mysql config file
  copy:
    src=../files/my.cnf
    dest=/etc/mysql/my.cnf
    mode=0444
  notify:
    - restart mysql

- include: supervisorify.yml
  vars:
    service: mysql
    command: /usr/sbin/mysqld
    procname: mysqld

- name: install mysql python library
  apt: pkg=python-mysqldb
