- name: install php5-fpm
  apt: pkg=php5-fpm

- name: setup central php5-fpm config for supervisor-friendly foreground mode
  copy: src=../files/php-fpm.conf
        dest=/etc/php5/fpm/php-fpm.conf
  notify:
    - restart php5-fpm

- name: update php.ini for php5-fpm
  copy: src=../files/php.ini
        dest=/etc/php5/fpm/php.ini
  notify:
    - restart php5-fpm

- include_tasks: supervisorify.yml
  vars:
    service: php5-fpm
    command: /usr/sbin/php5-fpm
