- name: access modern nodejs repository
  apt_repository: repo=ppa:chris-lea/node.js
  register: nodejs_repo

- name: update apt cache for nodejs repo
  apt: update_cache=yes
  when: nodejs_repo.changed

- name: install nodejs
  apt: pkg=nodejs
