

- name: remove package
  apt: name=haproxy state=absent
  tags: 
    - haproxy_install

- name: install haproxy
  apt: name=haproxy state=present update_cache=yes
  tags: 
    - haproxy_install

#- name: download haproxy deb file
#  get_url: url=http://debian.byte-consult.be/haproxy_1.5-dev17_amd64.deb
#           dest=/root/haproxy.deb

#- name: install haproxy
#  command: dpkg -i /root/haproxy.deb creates=/usr/sbin/haproxy

- include: supervisorify.yml
  vars:
    service: haproxy
    command: /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -db
