- name: install php5-fpm
  apt: pkg=php5-fpm
  register: php5_fpm_bin

- name: stop php5-fpm after installation
  service: name=php5-fpm state=stopped
  when: php5_fpm_bin.changed
  ignore_errors: yes

- name: disable naive php5-fpm init script
  file: path=/etc/rc2.d/S20php5-fpm state=absent

- name: configure php5-fpm with supervisor
  copy: src=common/files/php5-fpm-supervisor.conf
        dest=/etc/supervisor/conf.d/php5-fpm-supervisor.conf
  notify:
    - reload supervisor config

- name: setup central php5-fpm config for supervisor-friendly foreground mode
  copy: src=common/files/php-fpm.conf
        dest=/etc/php5/fpm/php-fpm.conf
  notify:
    - restart php5-fpm
