- name: install rabbitmq-server
  apt: pkg=rabbitmq-server

- include: supervisorify.yml
  vars:
    service: rabbitmq-server
    command: /usr/lib/rabbitmq/bin/rabbitmq-server
    daemon_environment: HOME=/tmp
