- name: install mysql
  apt: pkg=mysql-server
  become: yes

- name: install mysql config file
  copy:
    src=../files/my.cnf
    dest=/etc/mysql/my.cnf
    mode=0444
  become: yes
    
# SWITCH TO RUNIT
- name: create runit service directories for mysql
  file: path=/etc/service/mysql/supervise state=directory mode=0700 owner=root group=root

- name: set mysql under runit control
  copy: src=../files/mysql-runit.sh
        dest=/etc/service/mysql/run
        mode=0500
  when: dockerized

- name: install mysql python library
  pip: name=mysqlclient
  environment:
    MYSQLCLIENT_CFLAGS: "-I/usr/include/mysql"
    MYSQLCLIENT_LDFLAGS: "-L/usr/lib/x86_64-linux-gnu -lmysqlclient"

- name: Create mysql user
  mysql_user:
     name: mysql
     password: 'mysql'
     priv: '*.*:ALL,GRANT'
