- name: install redis-server {{redis_name|default('default')}}
  apt: pkg=redis-server

- name: set up redis.conf {{redis_name|default('default')}}
  template: src=../templates/redis.conf.j2 dest=/etc/redis/redis-{{redis_name|default('default')}}.conf
  notify:
    - restart redis # FIXME This will only work for the default redis

- include: supervisorify.yml
  vars:
    service: redis-{{redis_name|default('default')}}
    command: /usr/bin/redis-server /etc/redis/redis-{{redis_name|default('default')}}.conf
    procname: redis-server
