- name: install mongodb
  apt: pkg=mongodb

- include: supervisorify.yml
  vars:
    service: mongodb
    command: "/usr/bin/mongod --config /etc/mongodb.conf {{ '--smallfiles' if small_files is defined else ''}}"
    procname: mongod
