- name: install mysql
  apt: pkg=mysql-server

- name: install mysql_config
  apt: pkg=libmysqlclient-dev

# DITCH SUPERVISOR
# - include: supervisorify.yml
#   vars:
#     service: mysql
#     command: /usr/sbin/mysqld
#     procname: mysqld

# SWITCH TO RUNIT
- name: set mysql under runit control
  copy: src=../files/mysql-runit.sh
        dest=/etc/service/mysql/run
        mode=0500
  when: dockerized

- name: install mysql config file
  copy:
    src=../files/my.cnf
    dest=/etc/mysql/my.cnf
    mode=0444

- name: install mysql python library
  pip: name=mysqlclient
