- name: install redis-server {{redis_name|default('default')}}
  apt: pkg=redis-server

- name: set up redis.conf {{redis_name|default('default')}}
  template: src=../templates/redis.conf.j2 dest=/etc/redis/{{redis_name|default('default')}}.conf

# SWITCH TO RUNIT

- name: set redis-default under runit supervision
  shell: |
    mkdir -p /etc/sv/redis-{{redis_name|default('default')}}
    mkdir -p /etc/sv/redis-{{redis_name|default('default')}}/log
    echo '#!/bin/sh' > /etc/sv/redis-{{redis_name|default('default')}}/run
    echo 'exec /usr/bin/redis-server /etc/redis/redis-{{redis_name|default('default')}}.conf' >> /etc/sv/{{redis_name|default('default')}}/run
    chmod +x /etc/sv/redis-{{redis_name|default('default')}}/run
    rm /etc/service/redis-{{redis_name|default('default')}}
    ln -s /etc/sv/redis-{{redis_name|default('default')}} /etc/service/

