- name: install rabbitmq-server
  apt: pkg=rabbitmq-server

- include: supervisorify.yml
  vars:
    service: rabbitmq-server
    command: /usr/lib/rabbitmq/bin/rabbitmq-server
    procname: beam # FIXME: Would be nice to get only the Erlang proc running rabbit
    daemon_environment: HOME=/tmp
