- name: install nginx
  apt: pkg=nginx

- name: delete default nginx app
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

- name: setup central nginx config
  template: src=../templates/nginx.conf.j2
            dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- include: supervisorify.yml
  vars:
    service: nginx
    command: /usr/sbin/nginx
    start_secs: 5
