- name: install build-essential for building native ruby gems
  apt: pkg=build-essential

- name: install cmake for building native ruby gems
  apt: pkg=cmake

- name: install MySQL libraries for building mysql client gems
  apt: pkg=libmysqlclient-dev

- name: install SQLite3 libraries for building mysql client gems
  apt: pkg=libsqlite3-dev

- name: add apt repository for ruby 2.3
  apt_repository: repo=ppa:brightbox/ruby-ng

- name: install ruby 2
  apt: pkg=ruby2.3

- name: install ruby 2 dev
  apt: pkg=ruby2.3-dev

- name: install bundler gem
  gem: name=bundler state=present user_install=no
