- name: install php5-dev
  apt: pkg=php5-dev
  notify:
    - restart php5-fpm

- name: install PHP xmlrpc module
  apt: pkg=php5-xmlrpc
  notify:
    - restart php5-fpm

- name: install PHP mysql driver
  apt: pkg=php5-mysql
  notify:
    - restart php5-fpm

- name: install PHP mongo driver
  apt: pkg=php5-mongo
  notify:
    - restart php5-fpm

- name: install php5-cli
  apt: pkg=php5-cli

- name: install composer
  shell: curl -s http://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
         creates=/usr/local/bin/composer.phar
