- name: access modern PHP PPA
  apt_repository: repo=ppa:ondrej/php5

- name: install PHP 5 packages
  apt: pkg={{item}}
  with_items:
    - php5-dev
    - php5-cli
    - php5-xmlrpc
    - php-apc
    - php5-mysql
    - php5-mongo
    - php5-curl
    - php5-intl
    - php5-gmp

- name: set up configuration symlink for PHP mongo driver
  file: src=/etc/php5/mods-available/mongo.ini
        dest=/etc/php5/conf.d/mongo.ini
        state=link

- name: install composer
  shell: curl -s http://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
         creates=/usr/local/bin/composer.phar

- name: update php.ini for php5-cli
  copy: src=../files/php.ini dest=/etc/php5/cli/php.ini
