- name: install grunt 
  command: npm install grunt 
  tags: node_install

- name: install grunt-cli 0.1.6
  command: npm install -g grunt-cli@0.1.6 creates=/usr/lib/node_modules/grunt-cli/package.json