- name: install redis-server {{redis_name|default('default')}}
  apt: pkg=redis-server

- name: set up redis.conf {{redis_name|default('default')}}
  template: src=../templates/redis.conf.j2 dest=/etc/redis/redis-default.conf
  
- include: supervisorify.yml
  vars:
    service: redis-default
    command: /usr/bin/redis-server /etc/redis/redis-default.conf
    procname: redis-server
