- include: install_nodejs.yml

# this is redundant, doe it matter?
- include: install_grunt.yml
- include: install_gulp.yml

- include: install_bower.yml

- include: install_ruby.yml

- name: install haml gem
  gem: name=haml state=present user_install=no

- name: install sass gem
  gem: name=sass state=present user_install=no

- name: install sass-css-importer gem
  gem: name=sass-css-importer state=present version=1.0.0.beta.0 user_install=no
