- include: sliding_deploy_pull.yml
  vars:
    # Passing through: app_dir, name, user, git_url, version, shared_dirs
    copied_dirs: [ "vendor" ]

- name: sliding_deploy_symfony {{name}} - parameters template to config folder
  template: src="templates/secure/{{params_template}}"
        dest="{{app_dir}}/deployments/{{name}}/setup/app/config/parameters.yml"

- include: init_symfony_app.yml
  vars:
    dir: "{{app_dir}}/deployments/{{name}}/setup"

- name: sliding_symfony_deploy {{name}} - clear caches
  command: php app/console cache:clear --env={{item}}
           chdir="{{app_dir}}/deployments/{{name}}/setup"
  with_items:
    - prod
    - dev

# Despite the 'removes' argument, this command removes no files.
# We just don't want to try to restart php-fpm if it's not installed.
- name: force php-fpm restart
  command: echo triggering restart of php-fpm
           removes=/etc/supervisor.d/php-fpm7.4-supervisor.conf
  notify:
    - restart php-fpm7.4

- include: sliding_deploy_apply.yml
  # Passing through vars: app_dir, name
