- include: sliding_deploy_pull.yml
  vars:
    # Passing through: app_dir, name, user, git_url, version, shared_dirs
    copied_dirs: [ "vendor" ]

- name: sliding_deploy_symfony {{name}} - copy parameters.yml to config folder
  copy: src="files/secure/{{params_file}}"
        dest="{{app_dir}}/deployments/{{name}}/setup/app/config/parameters.yml"

- include: init_symfony_app.yml
  vars:
    dir: "{{app_dir}}/deployments/{{name}}/setup"

- name: sliding_symfony_deploy {{name}} - clear caches
  command: php app/console cache:clear --env={{item}}
           chdir="{{app_dir}}/deployments/{{name}}/setup"
  with_items:
    - prod
    - dev

- include: sliding_deploy_apply.yml
  # Passing through vars: app_dir, name
