- name: sliding_deploy_apply {{name}} - examine active deployment
  stat: path="{{app_dir}}/deployments/{{name}}/setup" follow=yes
  register: deploy_stat

- name: sliding_deploy_apply {{name}} - examine temporary symlink
  stat: path="{{app_dir}}/deployments/{{name}}/setup" follow=no
  register: symlink_stat

- name: sliding_deploy_apply {{name}} - remove temporary symlink
  file: path="{{app_dir}}/deployments/{{name}}/setup"
        state=absent

- name: sliding_deploy_apply {{name}} - set ownership of the repository again
  file: path="{{symlink_stat.stat.lnk_source}}"
        state=directory
        recurse=yes
        owner="{{deploy_stat.stat.uid}}"
        group="{{deploy_stat.stat.gid}}"

# TODO: Notify stuff (can we accept as an argument the handlers to notify?)
- name: sliding_deploy_apply {{name}} - update deployment symlink
  file: src="{{symlink_stat.stat.lnk_source}}"
        dest="{{app_dir}}/{{name}}"
        state=link

# TODO: Remove old deployments
