- name: sliding_deploy_pull {{name}} - create deployments directory
  file: path="{{app_dir}}/deployments/{{name}}"
        state=directory
        owner="{{ ansible_ssh_user }}"
        group="{{ ansible_ssh_user }}"

- name: sliding_deploy_pull {{name}} - create shared_dirs directory
  file: path="{{app_dir}}/deployments/{{name}}/shared_dirs"
        state=directory
        owner="{{ ansible_ssh_user }}"
        group="{{ ansible_ssh_user }}"

- name: sliding_deploy_pull {{name}} - delete old temporary repo directory
  become: yes
  file: path="{{app_dir}}/deployments/{{name}}/temp"
        state=absent

- name: create /root/.ssh directory
  become: yes
  file: path=/root/.ssh/ state=directory owner=root group=root

- name: sliding_deploy_pull {{name}} - clone repository
  git: repo="{{git_url}}"
       dest="{{app_dir}}/deployments/{{name}}/temp"
       version="{{version}}"
       depth=1
       accept_hostkey=true
  environment:
    GIT_SSH_COMMAND: "ssh -o ForwardAgent=yes"
  register: git_clone

- name: sliding_deploy_pull {{name}} - setup deployment name
  become: yes
  set_fact:
    deploy_dir: "{{app_dir}}/deployments/{{name}}/d-{{ansible_date_time.iso8601 | replace(':','.')}}-{{version}}-{{git_clone.after}}"

- name: Configure Git to trust the repository directory
  command: git config --global --add safe.directory "{{ deploy_dir }}"
  become_user: "{{ ansible_ssh_user }}"

- name: Ensure gems directory exists
  vars:
    gems_dir: /home/ubuntu/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/bundler/gems
  file:
    path: "{{ gems_dir }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Recursively find all directories in the gems directory
  vars:
    gems_dir: /home/ubuntu/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/bundler/gems
  find:
    paths: "{{ gems_dir }}"
    file_type: directory
  register: git_gem_directories

- name: Add each gem directory to Git safe.directory
  command: git config --global --add safe.directory "{{ item.path }}"
  with_items: "{{ git_gem_directories.files }}"
  become: yes
  become_user: "{{ ansible_ssh_user }}"

- name: sliding_deploy_pull {{name}} - rename repository to correct deployment name
  become: yes
  command: mv "{{app_dir}}/deployments/{{name}}/temp" "{{deploy_dir}}"
           removes="{{app_dir}}/deployments/{{name}}/temp"

- name: sliding_deploy_pull {{name}} - set ownership of the repository
  become: yes
  file: path="{{deploy_dir}}"
        state=directory
        recurse=yes
        owner="{{ ansible_ssh_user }}"
        group="{{ ansible_ssh_user }}"

- name: sliding_deploy_pull {{name}} - create temporary symlink to latest version
  become: yes
  file: src="{{deploy_dir}}"
        dest="{{app_dir}}/deployments/{{name}}/setup"
        state=link

# NOTE: This uses the 'removes' tag to avoid running the command unless the item
# exists; it does not actually remove anything.
- name: sliding_deploy_pull {{name}} - copy previously generated data
  become: yes
  command: rsync -a {{name}}/{{item}} {{deploy_dir}}
           chdir="{{app_dir}}" removes="{{app_dir}}/{{name}}/{{item}}"
  with_items: copied_dirs

- name: sliding_deploy_pull {{name}} - create shared directories
  become: yes
  file: path="{{app_dir}}/deployments/{{name}}/shared_dirs/{{item}}"
        state=directory
        owner="{{ ansible_ssh_user }}"
        group="{{ ansible_ssh_user }}"
  with_items: shared_dirs

- name: sliding_deploy_pull {{name}} - symlink shared directories
  become: yes
  file: src="{{app_dir}}/deployments/{{name}}/shared_dirs/{{item}}"
        dest="{{deploy_dir}}/{{item}}"
        state=link
  with_items: shared_dirs
