- include: sliding_deploy_pull.yml
  vars:
    # Passing through: name, user, git_url, version
    shared_dirs: []
    copied_dirs: [ "bower_components", "node_modules" ]

- name: sliding_deploy_angular {{name}} - copy settings.coffee to scripts folder
  copy: src="{{settings_file}}"
        dest="{{app_dir}}/deployments/{{name}}/setup/app/scripts/settings.coffee"

- name: sliding_deploy_angular {{name}} - install npm dependencies
  command: npm install --unsafe-perm
           chdir="{{app_dir}}/deployments/{{name}}/setup"

- name: sliding_deploy_angular {{name}} - install bower dependencies
  command: bower install --dev --allow-root
           chdir="{{app_dir}}/deployments/{{name}}/setup"

- name: sliding_deploy_angular {{name}} - build dist
  command: grunt build
           chdir="{{app_dir}}/deployments/{{name}}/setup"

# TODO: Run some kind of setup script provided by the app, if it's present

- include: sliding_deploy_apply.yml
