- include: install_php5_fpm.yml

- include: ferm_allow_global_port.yml
  vars:
    port: 80

- include: init_symfony_app.yml
  # Passing through variable: dir

- name: symfony_dev_server - reset ownership of the cache
  file: path="/dev/shm/ac"
        state=directory
        recurse=yes
        owner="{{name}}"
        group="{{name}}"

- include: symfony_app_user.yml
  vars:
    user: "{{name}}"

- include: nginx_app_config.yml
  vars:
    # Passing through variable: name
    template: common/templates/symfony-dev-nginx.j2
    root: "{{dir}}/web"
    symfony_devmode: true
    port: 80
