- include: init_symfony_app.yml
  # Passing through variable: dir

- include: supervisorify.yml
  vars:
    service: "{{name}}"
    command: "/usr/bin/php5 ./app/console server:run -vvv --env={{symfony_env|default('dev')}} {{ansible_eth1.ipv4.address}}:{{port|default('80')}}"
    chdir: "{{dir}}"
    stop_as_group: true
