- include: ferm_allow_global_port.yml
  vars:
    port: 80

- include: init_symfony_app.yml
  # Passing through variable: dir

- include: supervisorify.yml
  vars:
    service: "{{name}}"
    command: "/usr/bin/php5 ./app/console server:run -vvv --env={{symfony_env|default('dev')}} 0.0.0.0:80"
    chdir: "{{dir}}"
    stop_as_group: true
