- name: symfony_app_user {{user}} - create app user
  user: name={{user}} groups=www-data shell=/bin/bash

- name: symfony_app_user {{user}} - add www-data user to app user group
  user: name=www-data groups=www-data,{{user}}

- name: symfony_app_user {{user}} - set php-fpm to run a pool as the app user
  template: src=../templates/php-fpm-pool.conf.j2
            dest=/etc/php5/fpm/pool.d/{{user}}.conf
  ignore_errors: true # If php-fpm isn't installed, don't worry about it
  notify:
    - restart php5-fpm

- name: symfony_app_user {{user}} - delete default php-fpm pool
  file: path=/etc/php5/fpm/pool.d/www.conf state=absent
  ignore_errors: true # If php-fpm isn't installed, don't worry about it
  notify:
    - restart php5-fpm
