- include: install_php5_fpm.yml

- include: ferm_allow_global_port.yml
  vars:
    port: "{{web_port|default(80)}}"
  when: "not {{dockerized}}"

- include: symfony_app_user.yml
  vars:
    user: vagrant
    poolname: "{{name}}"

- include: init_symfony_app.yml
  # Passing through variable: dir

- name: symfony_dev_server - create cache directory
  file: path="/dev/shm/ac"
        state=directory
        recurse=yes
        owner=vagrant
        group=vagrant

- include: nginx_app_config.yml
  vars:
    # Passing through variable: name
    template: common/templates/symfony-dev-nginx.j2
    root: "{{dir}}/web"
    symfony_devmode: "{{!test_env|default(true)}}"
    symfony_testmode: "{{test_env|default(false)}}"
    port: "{{web_port|default(80)}}"
