- include: set_hostname.yml

- name: set shell prompt to show full hostname with production tag
  lineinfile: dest={{item}}
              regexp="^export PS1="
              line='export PS1="\[\033[1;31m\][PROD]\[\033[0m\] \u@\H:\w\$ "'
  with_items:
    - /etc/skel/.bashrc
    - /home/control/.bashrc
    - /root/.bashrc
  when: "{{production}}"

- name: set shell prompt to show full hostname without production tag
  lineinfile: dest={{item}}
              regexp="^export PS1="
              line='export PS1="\u@\H:\w\$ "'
  with_items:
    - /etc/skel/.bashrc
    - /home/control/.bashrc
    - /root/.bashrc
  when: "not {{production}}"

- name: allow ssh key forwarding through sudo
  lineinfile: dest=/etc/sudoers
              line="Defaults env_keep+=SSH_AUTH_SOCK"
              regexp="Defaults env_keep\\+=SSH_AUTH_SOCK"
              insertafter="^Defaults"

- name: install pycurl
  apt: pkg=python-pycurl

- name: access modern git repository
  apt_repository: repo=ppa:git-core/ppa

- name: add github ssh host key
  copy: src=../files/ssh_known_hosts
        dest=/etc/ssh/ssh_known_hosts
        mode=0444

- name: update apt cache
  apt: update_cache=yes

- name: install git
  apt: pkg=git

- name: install pip
  apt: pkg=python-pip

- name: update pip
  command: pip install --upgrade pip

- name: install supervisor
  apt: pkg=supervisor

- name: install supervisor_twiddler rpc extension
  pip: name=supervisor_twiddler extra_args="--no-deps"
  notify:
    - hard restart supervisor

- name: configure supervisor_twiddler
  copy: src=common/files/twiddler.conf
        dest=/etc/supervisor/conf.d/twiddler.conf
  notify:
    - hard restart supervisor

- name: install rsyslog config
  copy: src=../files/rsyslog.conf
        dest=/etc/rsyslog.conf
  notify:
    - restart rsyslog
