- name: generate locale
  command: locale-gen en_US.UTF-8 creates=/var/lib/locales/supported.d/local

- name: set locale
  command: update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
           creates=/etc/default/locale

- name: set /etc/localtime
  file: src=/usr/share/zoneinfo/{{timezone|default('America/New_York')}}
        dest=/etc/localtime
        state=link
        force=yes

- name: set /etc/timezone
  template: src=../templates/timezone.j2 dest=/etc/timezone
  notify: update tzdata

- name: create wtmp file
  command: touch /var/log/wtmp creates=/var/log/wtmp

- name: create lastlog file
  command: touch /var/log/lastlog creates=/var/log/lastlog

- name: set shell prompt to show full hostname with production tag
  lineinfile: dest={{item}}
              regexp="^export PS1="
              line='export PS1="\[\033[1;31m\][PROD]\[\033[0m\] \u@\H:\w\$ "'
  with_items:
    - "/etc/skel/.bashrc"
    - "/home/{{ansible_ssh_user}}/.bashrc"
    - "/root/.bashrc"
  when: "{{production}}"

- name: set shell prompt to show full hostname without production tag
  lineinfile: dest={{item}}
              regexp="^export PS1="
              line='export PS1="\u@\H:\w\$ "'
  with_items:
    - "/etc/skel/.bashrc"
    - "/home/{{ansible_ssh_user}}/.bashrc"
    - "/root/.bashrc"
  when: "not {{production}}"

- name: allow ssh key forwarding through sudo
  lineinfile: dest=/etc/sudoers
              line="Defaults env_keep+=SSH_AUTH_SOCK"
              regexp="Defaults env_keep\\+=SSH_AUTH_SOCK"
              insertafter="^Defaults"

- name: add github ssh host key
  copy: src=../files/ssh_known_hosts
        dest=/etc/ssh/ssh_known_hosts
        mode=0444

- name: update apt cache
  apt: update_cache=yes

- name: install ntp daemon
  apt: pkg=chrony
  notify:
    - restart chrony

- name: configure ntp daemon
  copy: src=../files/chrony.conf
        dest=/etc/chrony/chrony.conf
        mode=0644
        owner=root
        group=root
  notify:
    - restart chrony

- name: install pycurl
  apt: pkg=python-pycurl

- name: access modern git repository
  apt_repository: repo=ppa:git-core/ppa

- name: install git
  apt: pkg=git

- name: install pip
  apt: pkg=python-pip

- name: install git setuptools
  apt: pkg=python-setuptools-git

- name: update pip
  pip: name=pip state=latest

- name: remove rsyslog
  apt: pkg=rsyslog state=absent

- name: install syslog-ng
  apt: pkg=syslog-ng state=present

- name: set up syslog-ng config
  copy: src=../files/syslog-ng.conf
        dest=/etc/syslog-ng/syslog-ng.conf
  notify:
    - reload syslog-ng

- name: set a cron job to clear out old log files
  copy: src=../files/logclean.cron
        dest=/etc/cron.d/logclean
        mode=0444
        owner=root
        group=root

- name: remove landscape
  apt: pkg=landscape-common state=absent

- name: remove consolekit
  apt: pkg=consolekit state=absent

- name: install ferm
  tags: firewall
  apt: pkg=ferm
  notify:
    - reload firewall

- name: configure default ferm firewall rules
  tags: firewall
  copy: src=../files/ferm.conf
        dest=/etc/ferm/ferm.conf
  notify:
    - reload firewall

- name: create ferm.d conf directory
  tags: firewall
  file: path=/etc/ferm/ferm.d state=directory
  notify:
    - reload firewall

# TODO: Remove these after all our machines no longer have this old package
- name: uninstall supervisor apt package
  apt: pkg=supervisor state=absent
  notify:
    - hard restart supervisor
- name: delete old supervisor conf directory
  file: path=/etc/supervisor/ state=absent
  notify:
    - hard restart supervisor
- name: delete old supervisor egg link
  file: path=/usr/local/lib/python2.7/dist-packages/supervisor.egg-link state=absent
  notify:
    - hard restart supervisor
- name: delete old supervisor temp src directory
  file: path=/tmp/src/supervisor state=absent
  notify:
    - hard restart supervisor

# FIXME: Would be nice to notify a supervisor restart after this, but pip seems
# to fire a notification even when nothing changes!
- name: install supervisor with full syslog support
  pip: name="git+http://github.com/samv/supervisor.git@5a2b85e609#egg=supervisor" state=present

- name: create supervisor config directory
  file: path=/etc/supervisor.d state=directory
  notify:
    - hard restart supervisor

- name: create supervisor log directories
  file: path=/var/log/supervisor/ state=directory
  notify:
    - hard restart supervisor

- name: create upstart configuration for supervisor
  copy: src=../files/supervisor-upstart.conf
        dest=/etc/init/supervisor.conf
  notify:
    - hard restart supervisor

- name: link init.d/supervisor to upstart-job
  file: src=/lib/init/upstart-job
        dest=/etc/init.d/supervisor
        state=link
        force=yes

- name: install supervisor config file
  copy: src=../files/supervisord.conf
        dest=/etc/supervisord.conf
  notify:
    - hard restart supervisor

- name: install supervisor_twiddler rpc extension
  pip: name=supervisor_twiddler extra_args="--no-deps"
  notify:
    - hard restart supervisor

- name: configure supervisor_twiddler
  copy: src=../files/twiddler.conf
        dest=/etc/supervisor.d/twiddler.conf
  notify:
    - hard restart supervisor
