- include: set_hostname.yml

- name: install pycurl
  apt: pkg=python-pycurl

- name: access modern git repository
  apt_repository: repo=ppa:git-core/ppa

- name: add github ssh host key
  copy: src=common/files/ssh_known_hosts
        dest=/etc/ssh/ssh_known_hosts
        mode=0444

- name: update apt cache
  apt: update_cache=yes

- name: install git
  apt: pkg=git

- name: install supervisor
  apt: pkg=supervisor

- name: install pip
  apt: pkg=python-pip

- name: update pip
  command: pip install --upgrade pip

- name: install supervisor_twiddler rpc extension
  pip: name=supervisor_twiddler extra_args="--no-deps"
  notify:
    - hard stop supervisor
    - hard start supervisor

- name: configure supervisor_twiddler
  copy: src=common/files/twiddler.conf
        dest=/etc/supervisor/conf.d/twiddler.conf
  notify:
    - hard stop supervisor
    - hard start supervisor

- name: install rsyslog config
  copy: src=common/files/rsyslog.conf
        dest=/etc/rsyslog.conf
  notify:
    - restart rsyslog
