- include_tasks: create_swapfile.yml

- name: install python-keyczar
  pip: name=python-keyczar

- name: cd to /vagrant after login
  lineinfile: dest=/home/vagrant/.bashrc
              regexp="^cd /vagrant"
              line="cd /vagrant"
