- include: create_swapfile.yml

- name: install python-keyczar
  command: pip3 install python-keyczar

- name: cd to /vagrant after login
  lineinfile: dest=/home/vagrant/.bashrc
              regexp="^cd /vagrant"
              line="cd /vagrant"
