- name: update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

- name: reload firewall
  service: name=ferm state=restarted

- name: hard restart supervisor
  service: name=supervisor state=restarted sleep=1

- name: reload syslog-ng
  service: name=syslog-ng state=reloaded

- name: restart nginx
  supervisorctl: name=nginx state=restarted

- name: restart mysql
  supervisorctl: name=mysql state=restarted

- name: restart haproxy
  supervisorctl: name=haproxy state=restarted

- name: restart php5-fpm
  supervisorctl: name=php5-fpm state=restarted

- name: restart rabbitmq-server
  supervisorctl: name=rabbitmq-server state=restarted

- name: restart redis
  supervisorctl: name=redis state=restarted

- name: restart mongodb
  supervisorctl: name=mongodb state=restarted

- name: restart elasticsearch
  supervisorctl: name=elasticsearch state=restarted
