- name: hard restart supervisor
  service: name=supervisor state=restarted sleep=1

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart nginx
  supervisorctl: name=nginx state=restarted

- name: restart mysql
  supervisorctl: name=mysql state=restarted

- name: restart haproxy
  supervisorctl: name=haproxy state=restarted

- name: restart php5-fpm
  supervisorctl: name=php5-fpm state=restarted

- name: restart rabbitmq
  supervisorctl: name=rabbitmq state=restarted

- name: restart mongodb
  supervisorctl: name=mongodb state=restarted
