interface=lo
bind-interfaces
addn-hosts=/etc/hosts_extra
pid-file=/var/run/dnsmasq/dnsmasq.pid
user=root
no-resolv
conf-dir=/etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new
expand-hosts

domain=actesting.org
server=ns-47.awsdns-05.com
server=ns-1806.awsdns-33.co.uk
server=ns-1136.awsdns-14.org
server=ns-668.awsdns-19.net
