#!/bin/sh

SERVICE=$(basename $0)


case "$1" in
  start)
    echo "Running: supervisorctl start $SERVICE"
    /usr/local/bin/supervisorctl start $SERVICE
    ;;
  stop)
    echo "Running: supervisorctl stop $SERVICE"
    /usr/local/bin/supervisorctl stop $SERVICE
    ;;
  restart|force-reload)
    echo "Running: supervisorctl restart $SERVICE"
    /usr/local/bin/supervisorctl restart $SERVICE
    ;;
  status)
    echo "Running: supervisorctl status $SERVICE"
    /usr/local/bin/supervisorctl status $SERVICE
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >@2
    exit 3
    ;;
esac
